apiVersion: apps/v1
kind: Deployment
metadata:
  name: jammy-deployment
  labels:
    app: jammy-server
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: jammy-server
  template:
    metadata:
      labels:
        app: jammy-server
    spec: 
      containers:
        - name: node
          image: sdmount/jammy-server
          ports:
            - containerPort: 22
